name: Echo Hello on Push

on:
  push:
    branches:
      - main  # Change this if needed

jobs:
  say-hello:
    runs-on: self-hosted  # Uses your local self-hosted runner
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Echo Hello
        run: echo "Hello"

